-- =====================================================================
-- AMORÇAGE DES RÉFÉRENTIELS — généré par backend/database/amorcage/generer.py
-- Ne pas éditer à la main : régénérer.
-- =====================================================================

-- ref.univers
insert into ref.univers (code, libelle_fr, couleur_primaire, couleur_secondaire, logo_url, logo_mini_url, talent_card_url, est_ouvert, ordre) values ('product', 'Product', '#FF8F67', '#FFD2C2', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771510531092x899340636151304100/Pacha-Product.svg', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771510554673x358838342030748160/Pacha-Product2.svg', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771506362128x264472943874164640/Product.png', true, 1);
insert into ref.univers (code, libelle_fr, couleur_primaire, couleur_secondaire, logo_url, logo_mini_url, talent_card_url, est_ouvert, ordre) values ('tech', 'Tech', '#AC8CFF', '#E9E0FF', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771510576432x141432531009232370/Pacha-Tech.svg', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771510568200x332533064825881100/Pacha-tech2.svg', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771506386757x137184172723513900/Tech.png', true, 2);
insert into ref.univers (code, libelle_fr, couleur_primaire, couleur_secondaire, logo_url, logo_mini_url, talent_card_url, est_ouvert, ordre) values ('design', 'Design', null, null, null, null, null, false, 3);
insert into ref.univers (code, libelle_fr, couleur_primaire, couleur_secondaire, logo_url, logo_mini_url, talent_card_url, est_ouvert, ordre) values ('data', 'Data', null, null, null, null, null, false, 4);
insert into ref.univers (code, libelle_fr, couleur_primaire, couleur_secondaire, logo_url, logo_mini_url, talent_card_url, est_ouvert, ordre) values ('finance', 'Finance', null, null, null, null, null, false, 5);
insert into ref.univers (code, libelle_fr, couleur_primaire, couleur_secondaire, logo_url, logo_mini_url, talent_card_url, est_ouvert, ordre) values ('people_et_finance', 'People & Finance', '#FFE94A', '#FFFBF0', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771510756972x825547768422245200/Pacha-People%26Fin.svg', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771510690181x222058179339188260/Pacha-People%26Fin2.svg', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771506405173x414471793432937840/Peaple.png', true, 6);
insert into ref.univers (code, libelle_fr, couleur_primaire, couleur_secondaire, logo_url, logo_mini_url, talent_card_url, est_ouvert, ordre) values ('marketing', 'Marketing', null, null, null, null, null, true, 7);
insert into ref.univers (code, libelle_fr, couleur_primaire, couleur_secondaire, logo_url, logo_mini_url, talent_card_url, est_ouvert, ordre) values ('sales', 'Sales', '#7AE7BF', '#CCF5E6', null, null, '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1771506436076x964991396767586400/Sales.png', true, 8);

-- ref.metier
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager', 'Product Manager', 1, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_product_manager', 'Senior Product Manager', 2, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_product_manager', 'Lead Product Manager', 3, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_product', 'Head of Product', 4, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_director', 'Product Director', 5, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('vp_product', 'VP Product', 6, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('cpo', 'CPO', 7, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_growth', 'Product Growth', 8, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_builder', 'Product Builder', 9, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_marketing_manager', 'Product Marketing Manager', 10, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_ops', 'Product Ops', 11, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_ops_manager', 'Product Ops Manager', 12, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ux_writing', 'UX Writing', 13, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ux_user_research', 'UX / User Research', 14, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_designer', 'Product Designer', 15, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_product_design', 'Head of Product Design', 16, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('entrepreneur', 'Entrepreneur', 17, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ceo', 'CEO', 18, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('co_fondateur', 'Co-fondateur', 19, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('hr_manager', 'HR Manager', 20, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('talent_acquisition_manager', 'Talent Acquisition Manager', 21, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ctpo', 'CTPO', 22, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('cto', 'CTO', 23, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('coo', 'COO', 24, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('cmo', 'CMO', 25, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chief_digital_transformation_officer', 'Chief Digital Transformation Officer', 26, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('vp_people', 'VP People', 27, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_digital_products', 'Head of Digital Products', 28, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_data_analyst', 'Product Data Analyst', 29, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ml_ops', 'ML Ops', 30, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_data_analytics', 'Product Data Analytics', 31, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('data_analyst', 'Data Analyst', 32, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('data_scientist', 'Data Scientist', 33, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_owner', 'Product Owner', 34, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_po', 'Lead PO', 35, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_dev', 'Lead Dev', 36, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_engineering', 'Head of Engineering', 37, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('developpeur_se_full_stack', 'Développeur.se Full Stack', 38, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('interim_cpo', 'Interim-CPO', 39, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_product_designer', 'Senior Product Designer', 41, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('scrum_master', 'Scrum Master', 42, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('po_mobile', 'PO Mobile', 43, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('po_core', 'PO Core', 44, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_product_designer', 'Lead Product Designer', 45, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_data', 'PM Data', 46, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sre_devops', 'SRE/devOps', 47, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('genai', 'GenAI', 48, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('data_eng', 'Data Eng.', 49, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('backend_engineer', 'Backend Engineer', 50, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_backend_eng', 'Lead Backend Eng.', 51, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_data', 'Product Manager Data', 52, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_ml', 'Product Manager ML', 53, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('r_et_d_manager', 'R&D Manager', 54, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('engineering_manager', 'Engineering Manager', 55, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('software_engineer', 'Software engineer', 56, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('founding_product_designer', 'Founding Product Designer', 57, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('founding_product_manager', 'Founding Product Manager', 58, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('phd_engineer', 'PhD Engineer', 59, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('frontend_software_engineer', 'Frontend Software Engineer', 60, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_medias', 'Product Manager Médias', 61, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_b2c', 'Product Manager B2C', 62, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_data_b2c', 'Product Manager Data / B2C', 63, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chief_financial_officer', 'Chief Financial Officer', 64, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('daf', 'DAF', 65, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directeur_rice_comptable', 'Directeur·rice Comptable', 66, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('responsable_comptable', 'Responsable Comptable', 67, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directeur_rice_achat', 'Directeur·rice Achat', 68, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('responsable_achat', 'Responsable Achat', 69, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chief_people_officer', 'Chief People Officer', 71, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('people_ops_manager', 'People Ops Manager', 72, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_people', 'Head of People', 74, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('responsable_rh', 'Responsable RH', 75, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directeur_rice_rh', 'Directeur·rice RH', 76, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_hr_manager', 'Senior HR Manager', 77, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chef_de_produit', 'Chef de produit', 79, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('bras_droit_du_cpo', 'Bras droit du CPO', 80, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('content_manager', 'Content Manager', 81, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('seo_manager', 'SEO Manager', 82, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_data', 'Head of Data', 83, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('vp_data', 'VP Data', 84, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('growth_manager', 'Growth Manager', 85, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('training_manager', 'Training Manager', 86, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('1st_product_manager', '1st Product Manager', 88, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('group_pm', 'Group PM', 89, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('consultant_sap', 'Consultant SAP', 90, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_ecommerce', 'Product Manager Ecommerce', 91, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_b2b2c', 'Product Manager B2B2C', 92, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_paiement', 'PM Paiement', 93, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('consultant_e_crm', 'Consultant(e) CRM', 94, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('charge_e_de_recrutement', 'Chargé.e de recrutement', 95, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('responsable_recrutement', 'Responsable recrutement', 96, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('charge_e_de_mission_si', 'Chargé.e de mission SI', 97, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_pm_b2c_mobile', 'Senior PM B2C / Mobile', 98, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_pm_banking_as_a_service', 'Senior PM Banking as a Service', 99, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_comptable', 'Senior Comptable', 100, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('manager_comptabilite', 'Manager Comptabilité', 101, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chargee_de_recrutement', 'Chargée de recrutement', 103, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('charge_de_recrutement', 'Chargé de recrutement', 104, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('rpo', 'RPO', 105, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('cx_ux_designer', 'CX / UX Designer', 106, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_banking_operations', 'Product Manager - Banking operations', 107, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chief_marketing_officer_cmo', 'Chief Marketing Officer (CMO)', 108, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chief_digital_officer_cdo', 'Chief Digital Officer (CDO)', 109, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('vp_marketing', 'VP Marketing', 110, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_architecture', 'Head of Architecture', 111, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_backend', 'Lead Backend', 112, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_marketing', 'Head of Marketing', 113, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_growth', 'Head of Growth', 115, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('growth_marketing_director', 'Growth Marketing Director', 116, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('digital_marketing_manager', 'Digital Marketing Manager', 117, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('performance_marketing_manager', 'Performance Marketing Manager', 118, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('growth_hacker', 'Growth Hacker', 119, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('social_media_manager', 'Social Media Manager', 120, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('content_marketing_manager', 'Content Marketing Manager', 121, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('brand_manager', 'Brand Manager', 122, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pr_et_communication_manager', 'PR & Communication Manager', 124, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('marketing_analyst', 'Marketing Analyst', 125, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('crm_manager', 'CRM Manager', 126, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('e_commerce_manager', 'E-commerce Manager', 127, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_acquisition', 'PM Acquisition', 128, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('mobile_engineer', 'Mobile Engineer', 129, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('architecte_solution', 'Architecte Solution', 130, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('cxo', 'CXO', 131, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('po_tech', 'PO Tech', 132, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('po_crm', 'PO CRM', 133, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('payment_operations_specialist', 'Payment Operations Spécialist', 134, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_pm_paiement_et_banking_experience', 'Lead PM - Paiement & Banking Experience', 135, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_pm_core_banking_system', 'Lead PM - Core Banking System', 136, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_fraud_et_transaction', 'PM - Fraud & Transaction', 137, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_pm_squad_payment_experience', 'Senior PM - Squad Payment Experience', 138, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('brand_designer', 'Brand Designer', 139, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_pm', 'Lead PM', 140, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('vp_of_engineering', 'VP of Engineering', 141, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('responsable_infrastructure', 'Responsable infrastructure', 142, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ai_product_specialist', 'AI Product Specialist', 144, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_owner_customer_service', 'Product Owner - Customer Service', 145, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_owner_product_et_pricing', 'Product Owner - Product & Pricing', 146, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_owner_customer_acquisition', 'Product Owner - Customer Acquisition', 147, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('staff_engineer', 'Staff Engineer', 148, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ml_engineer', 'ML Engineer', 149, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chief_scientific_officer', 'Chief Scientific Officer', 150, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ai_product_manager', 'AI Product Manager', 151, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('business_development_representative', 'Business Development Representative', 152, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pmm_director', 'PMM Director', 153, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('bdr_sdr_manager', 'BDR / SDR Manager', 154, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('account_manager', 'Account manager', 155, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('key_account_director', 'Key Account Director', 156, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sales_associate', 'Sales Associate', 160, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sales_inbound', 'Sales Inbound', 161, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sales_executive', 'Sales Executive', 162, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_account_executive', 'Senior Account Executive', 163, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('enterprise_account_executive', 'Enterprise Account Executive', 164, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('smb_account_executive', 'SMB Account Executive', 165, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('mid_market_account_executive', 'Mid-market Account Executive', 166, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ingenieur_commercial', 'Ingénieur commercial', 167, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('commercial_btob', 'Commercial BtoB', 168, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('team_leader_sales', 'Team leader Sales', 169, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sales_director', 'Sales Director', 171, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directeur_commercial', 'Directeur Commercial', 172, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('vp_sales', 'VP Sales', 173, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sales_enablement_manager', 'Sales Enablement Manager', 174, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sales_ops_manager', 'Sales Ops Manager', 175, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('revops_manager', 'RevOps Manager', 176, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_revops_sales_ops', 'Head of RevOps / Sales Ops', 177, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('inside_sales', 'Inside Sales', 180, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sales_manager', 'Sales Manager', 187, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('support_engineer', 'Support Engineer', 199, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('key_account_sales_executive', 'Key Account Sales Executive', 200, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_csm', 'Head of CSM', 201, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('tech_lead_ai', 'Tech Lead AI', 202, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_sales', 'Head of Sales', 203, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_business_developer', 'Senior Business Developer', 205, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('business_development_manager', 'Business Development Manager', 206, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directeur_general', 'Directeur Général', 207, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directrice_generale', 'Directrice Générale', 208, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_partnerships', 'Head of Partnerships', 209, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('team_lead_am', 'Team Lead AM', 210, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_java_developer', 'Senior Java Developer', 211, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('account_executive', 'Account Executive', 212, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_business_development', 'Head of Business Development', 213, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chef_de_projet_data', 'Chef de projet Data', 214, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chef_de_projet_data_et_flux', 'Chef de projet Data et Flux', 215, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_product_management', 'Head of Product Management', 216, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('sales_development_representative', 'Sales Development Representative', 217, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directrice_des_offres', 'Directrice des offres', 218, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('responsable_grands_comptes', 'Responsable Grands Comptes', 219, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directeur_des_offres', 'Directeur des offres', 220, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('customer_success_manager', 'Customer Success Manager', 221, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chef_de_produit_energie_renouvelable', 'Chef de produit énergie renouvelable', 222, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directeur_produit', 'Directeur Produit', 223, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('directrice_produit', 'Directrice Produit', 224, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_fintech', 'PM Fintech', 226, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_pm_fintech', 'Senior PM Fintech', 227, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pmm_head_of_marketing', 'PMM / Head of Marketing', 228, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('business_ops_manager', 'Business Ops Manager', 229, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_customer_experience', 'Head of Customer Experience', 230, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ai_engineer', 'AI Engineer', 231, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('key_account_manager', 'Key Account Manager', 232, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('program_director', 'Program Director', 233, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pmo', 'PMO', 234, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('project_manager', 'Project Manager', 235, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('manager_senior_manager_data_et_ai', 'Manager / Senior Manager Data & AI', 236, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_b2b', 'Product Manager - B2B', 237, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('android_engineer', 'Android Engineer', 238, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_talent_acquisition', 'Head of Talent Acquisition', 239, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_saas_b2b', 'Product Manager - SaaS B2B', 240, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_api', 'Product Manager - API', 241, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_technical_ops', 'Lead Technical Ops', 242, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_operations', 'Head of Operations', 243, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('customer_care', 'Customer Care', 244, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('developpeur_data', 'Développeur Data', 246, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('analytics_engineer', 'Analytics Engineer', 247, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_dev_fullstack', 'Lead Dev Fullstack', 248, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_ia', 'Product Manager IA', 249, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_pm_ia', 'Senior PM - IA', 250, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('product_manager_medtech', 'Product Manager - Medtech', 251, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_pm_medtech', 'Senior PM - Medtech', 252, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('senior_pm_medical_ai_samd', 'Senior PM – Medical AI / SaMD', 253, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('qa_analyst', 'QA Analyst', 254, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_background_tech', 'PM - background Tech', 255, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_domain', 'Head of Domain', 256, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('head_of_product_delivery', 'Head of Product Delivery', 257, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('cpo_consumer', 'CPO - Consumer', 258, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_btoc', 'PM BtoC', 259, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('dataops', 'DataOps', 260, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_full_stack_engineer_ai_et_agentic_ui', 'Lead Full Stack Engineer (AI & Agentic UI)', 261, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_conversion', 'PM Conversion', 262, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('business_secteur_lead_sport', 'Business Secteur Lead - Sport', 263, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ia_director', 'IA Director', 264, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('business_secteur_lead_culture', 'Business Secteur Lead - Culture', 265, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('ai_director', 'AI Director', 266, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('lead_data_engineer', 'Lead Data Engineer', 267, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('chief_data_officer', 'Chief Data Officer', 268, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('dev_backend_api', 'Dev Backend - API', 269, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('dev_php_fullstack', 'Dev PHP / Fullstack', 270, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('pm_discovery', 'PM Discovery', 271, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('tech_lead', 'Tech Lead', 272, 'referentiel');
insert into ref.metier (code, libelle_fr, ordre, origine) values ('tech_lead_react_native', 'Tech Lead React Native', 273, 'referentiel');

-- ref.expertise
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('genai', 'GenAI', 1, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('nocode', 'NoCode', 2, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('growth', 'Growth', 3, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('ia', 'IA', 4, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('data', 'Data', 5, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('early_stage', 'Early-stage', 6, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('design', 'Design', 7, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('impact', 'Impact', 8, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('internationalisation', 'Internationalisation', 9, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('ux', 'UX', 10, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('ui', 'UI', 11, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('design_system', 'Design System', 12, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('design_ops', 'Design Ops', 13, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('uxr', 'UXR', 14, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('sql', 'SQL', 15, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('python', 'Python', 16, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('machine_learning', 'Machine Learning', 17, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('c_sharp', 'C#', 18, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('c_plus_plus', 'C++', 19, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('nodejs', 'NodeJS', 20, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('typescript', 'TypeScript', 21, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('php', 'PHP', 22, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('reactjs', 'ReactJS', 23, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('vuejs', 'VueJS', 24, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('ruby', 'Ruby', 25, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('mobile', 'Mobile', 26, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('golang', 'Golang', 27, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('scala', 'Scala', 28, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('rust', 'Rust', 29, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('elixir', 'Elixir', 30, 'referentiel');
insert into ref.expertise (code, libelle_fr, ordre, origine) values ('n_a', 'N/A', 31, 'referentiel');

-- ref.secteur
insert into ref.secteur (code, libelle_fr, ordre) values ('adtech', 'Adtech', 1);
insert into ref.secteur (code, libelle_fr, ordre) values ('agritech', 'Agritech', 2);
insert into ref.secteur (code, libelle_fr, ordre) values ('beautytech', 'BeautyTech', 3);
insert into ref.secteur (code, libelle_fr, ordre) values ('blockchain_nft', 'Blockchain / NFT', 4);
insert into ref.secteur (code, libelle_fr, ordre) values ('biotech', 'Biotech', 5);
insert into ref.secteur (code, libelle_fr, ordre) values ('big_data', 'Big data', 6);
insert into ref.secteur (code, libelle_fr, ordre) values ('charity', 'Charity', 7);
insert into ref.secteur (code, libelle_fr, ordre) values ('cleantech', 'Cleantech', 8);
insert into ref.secteur (code, libelle_fr, ordre) values ('climatetech', 'ClimateTech', 9);
insert into ref.secteur (code, libelle_fr, ordre) values ('construction_tech', 'Construction Tech', 10);
insert into ref.secteur (code, libelle_fr, ordre) values ('consumer_goods', 'Consumer goods', 11);
insert into ref.secteur (code, libelle_fr, ordre) values ('cybersecurity', 'Cybersecurity', 12);
insert into ref.secteur (code, libelle_fr, ordre) values ('deeptech', 'Deeptech', 13);
insert into ref.secteur (code, libelle_fr, ordre) values ('ecommerce', 'Ecommerce', 14);
insert into ref.secteur (code, libelle_fr, ordre) values ('edtech', 'Edtech', 15);
insert into ref.secteur (code, libelle_fr, ordre) values ('energy', 'Energy', 16);
insert into ref.secteur (code, libelle_fr, ordre) values ('entertainment', 'Entertainment', 17);
insert into ref.secteur (code, libelle_fr, ordre) values ('fashiontech', 'Fashiontech', 18);
insert into ref.secteur (code, libelle_fr, ordre) values ('fintech', 'Fintech', 19);
insert into ref.secteur (code, libelle_fr, ordre) values ('foodtech', 'Foodtech', 20);
insert into ref.secteur (code, libelle_fr, ordre) values ('future_of_work', 'Future of work', 21);
insert into ref.secteur (code, libelle_fr, ordre) values ('gaming', 'Gaming', 22);
insert into ref.secteur (code, libelle_fr, ordre) values ('govtech', 'Govtech', 23);
insert into ref.secteur (code, libelle_fr, ordre) values ('greentech', 'Greentech', 24);
insert into ref.secteur (code, libelle_fr, ordre) values ('healthtech', 'Healthtech', 25);
insert into ref.secteur (code, libelle_fr, ordre) values ('hospitality', 'Hospitality', 26);
insert into ref.secteur (code, libelle_fr, ordre) values ('hrtech', 'HRtech', 27);
insert into ref.secteur (code, libelle_fr, ordre) values ('industry', 'Industry', 28);
insert into ref.secteur (code, libelle_fr, ordre) values ('ia', 'IA', 29);
insert into ref.secteur (code, libelle_fr, ordre) values ('insurtech', 'Insurtech', 30);
insert into ref.secteur (code, libelle_fr, ordre) values ('it', 'IT', 31);
insert into ref.secteur (code, libelle_fr, ordre) values ('legaltech', 'Legaltech', 32);
insert into ref.secteur (code, libelle_fr, ordre) values ('logistics_supply_chain', 'Logistics / Supply Chain', 33);
insert into ref.secteur (code, libelle_fr, ordre) values ('luxury', 'Luxury', 34);
insert into ref.secteur (code, libelle_fr, ordre) values ('media', 'Media', 35);
insert into ref.secteur (code, libelle_fr, ordre) values ('martech', 'Martech', 36);
insert into ref.secteur (code, libelle_fr, ordre) values ('medtech', 'Medtech', 37);
insert into ref.secteur (code, libelle_fr, ordre) values ('mobitech', 'Mobitech', 38);
insert into ref.secteur (code, libelle_fr, ordre) values ('productivity_tools', 'Productivity tools', 39);
insert into ref.secteur (code, libelle_fr, ordre) values ('proptech', 'Proptech', 40);
insert into ref.secteur (code, libelle_fr, ordre) values ('regtech', 'Regtech', 41);
insert into ref.secteur (code, libelle_fr, ordre) values ('retail', 'Retail', 42);
insert into ref.secteur (code, libelle_fr, ordre) values ('sales_tech', 'Sales-tech', 43);
insert into ref.secteur (code, libelle_fr, ordre) values ('smart_city', 'Smart city', 44);
insert into ref.secteur (code, libelle_fr, ordre) values ('spacetech', 'Spacetech', 45);
insert into ref.secteur (code, libelle_fr, ordre) values ('sportech', 'Sportech', 46);
insert into ref.secteur (code, libelle_fr, ordre) values ('telco', 'Telco', 47);
insert into ref.secteur (code, libelle_fr, ordre) values ('traveltech', 'Traveltech', 48);
insert into ref.secteur (code, libelle_fr, ordre) values ('web3_crypto', 'Web3 / crypto', 49);
insert into ref.secteur (code, libelle_fr, ordre) values ('developer_tools', 'Developer tools', 50);
insert into ref.secteur (code, libelle_fr, ordre) values ('hardware', 'Hardware', 51);
insert into ref.secteur (code, libelle_fr, ordre) values ('consulting_services', 'Consulting / Services', 52);

-- ref.critere
insert into ref.critere (code, libelle_fr, ordre) values ('ambition', 'Ambition', 1);
insert into ref.critere (code, libelle_fr, ordre) values ('app_mobile', 'App Mobile', 2);
insert into ref.critere (code, libelle_fr, ordre) values ('autonomie', 'Autonomie', 3);
insert into ref.critere (code, libelle_fr, ordre) values ('challenge_intellectuel', 'Challenge intellectuel', 4);
insert into ref.critere (code, libelle_fr, ordre) values ('confiance_dans_la_vision_fondateurs', 'Confiance dans la vision fondateurs', 5);
insert into ref.critere (code, libelle_fr, ordre) values ('creer_un_produit_from_scratch', 'Créer un produit from scratch', 6);
insert into ref.critere (code, libelle_fr, ordre) values ('culture_non_toxique', 'Culture non toxique', 7);
insert into ref.critere (code, libelle_fr, ordre) values ('culture_produit_tres_forte', 'Culture Produit très forte', 8);
insert into ref.critere (code, libelle_fr, ordre) values ('decouvrir_un_nouveau_contexte', 'Découvrir un nouveau contexte', 9);
insert into ref.critere (code, libelle_fr, ordre) values ('equilibre_vie_pro_perso', 'Equilibre vie pro-perso', 10);
insert into ref.critere (code, libelle_fr, ordre) values ('exigence_performance', 'Exigence / Performance', 11);
insert into ref.critere (code, libelle_fr, ordre) values ('feeling_avec_l_equipe', 'Feeling avec l''équipe', 12);
insert into ref.critere (code, libelle_fr, ordre) values ('finances_saines', 'Finances saines', 13);
insert into ref.critere (code, libelle_fr, ordre) values ('full_remote_obligatoire', 'Full-remote obligatoire', 14);
insert into ref.critere (code, libelle_fr, ordre) values ('impact_dans_une_boite_jeune', 'Impact dans une boîte jeune', 15);
insert into ref.critere (code, libelle_fr, ordre) values ('international', 'International', 16);
insert into ref.critere (code, libelle_fr, ordre) values ('localisation', 'Localisation', 17);
insert into ref.critere (code, libelle_fr, ordre) values ('management_bienveillant', 'Management bienveillant', 18);
insert into ref.critere (code, libelle_fr, ordre) values ('management_indispensable', 'Management indispensable', 19);
insert into ref.critere (code, libelle_fr, ordre) values ('petite_structure', 'Petite structure', 20);
insert into ref.critere (code, libelle_fr, ordre) values ('problematiques_complexes', 'Problématiques complexes', 21);
insert into ref.critere (code, libelle_fr, ordre) values ('produit_au_coeur_du_business', 'Produit au coeur du Business', 22);
insert into ref.critere (code, libelle_fr, ordre) values ('produit_technique', 'Produit technique', 23);
insert into ref.critere (code, libelle_fr, ordre) values ('rejoindre_une_equipe', 'Rejoindre une équipe', 24);
insert into ref.critere (code, libelle_fr, ordre) values ('sens_impact_produit_utile', 'Sens / Impact / Produit utile', 25);
insert into ref.critere (code, libelle_fr, ordre) values ('simplifier_de_la_complexite', 'Simplifier de la complexité', 26);
insert into ref.critere (code, libelle_fr, ordre) values ('startup_hype', 'Startup hype', 27);
insert into ref.critere (code, libelle_fr, ordre) values ('team_feminine', 'Team féminine', 28);
insert into ref.critere (code, libelle_fr, ordre) values ('team_forte_autour', 'Team forte autour', 29);
insert into ref.critere (code, libelle_fr, ordre) values ('trajectoire_carriere_avec_management', 'Trajectoire carrière avec management', 30);
insert into ref.critere (code, libelle_fr, ordre) values ('4_5_indispensable', '4/5 indispensable', 31);
insert into ref.critere (code, libelle_fr, ordre) values ('xp_utilisateur_au_coeur', 'XP utilisateur au coeur', 32);

-- ref.maturite_produit
insert into ref.maturite_produit (code, libelle_fr, image_url, ordre) values ('a', 'A', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1685906978805x102263818870296450/2.png', 1);
insert into ref.maturite_produit (code, libelle_fr, image_url, ordre) values ('b', 'B', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1685906984257x592038767538212400/3.png', 2);
insert into ref.maturite_produit (code, libelle_fr, image_url, ordre) values ('c', 'C', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1685906988857x855593364964368800/4.png', 3);
insert into ref.maturite_produit (code, libelle_fr, image_url, ordre) values ('d', 'D', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1685906993227x308368848102106300/5.png', 4);
insert into ref.maturite_produit (code, libelle_fr, image_url, ordre) values ('e', 'E', '//98119bfbf8cfc027dc70db6c69918bd3.cdn.bubble.io/f1685906998068x260210436399202180/6.png', 5);

-- ref.statut_contrat
insert into ref.statut_contrat (code, libelle_fr, emoji, couleur, signature_requise, ordre) values ('contrat_non_signe', 'Contrat non signé', '⏳', '#F47777', true, 1);
insert into ref.statut_contrat (code, libelle_fr, emoji, couleur, signature_requise, ordre) values ('contrat_envoye', 'Contrat envoyé', '📥', '#6B55D8', true, 2);
insert into ref.statut_contrat (code, libelle_fr, emoji, couleur, signature_requise, ordre) values ('contrat_signe', 'Contrat signé', '✅', '#81CF81', false, 3);
insert into ref.statut_contrat (code, libelle_fr, emoji, couleur, signature_requise, ordre) values ('contrat_expire', 'Contrat expiré', '❌', '#F47777', true, 4);
insert into ref.statut_contrat (code, libelle_fr, emoji, couleur, signature_requise, ordre) values ('not_required', 'Not required', '✅', null, false, 5);

-- ref.evenement_note — note_event_type est vide au miroir : le type est
-- déduit du préfixe du code, ce que la contrainte CHECK exige de toute façon.
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('contract_free_update', 'contract', 'Mise à jour du contrat freelance', 1);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('contract_cus_update', 'contract', 'Mise à jour du contrat client', 2);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('info_closing_date', 'info', 'Mise à jour de la date de closing', 3);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('info_salary', 'info', 'Mise à jour du salaire', 4);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('info_rate', 'info', 'Mise à jour du TJM (marge incluse)', 5);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('info_rate_talent', 'info', 'Mise à jour du TJM (talent)', 6);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('info_com', 'info', 'Mise à jour de la commission à facturer', 7);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('info_start_date', 'info', 'Mise à jour de la date de début', 8);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('info_end_date_free', 'info', 'Mise à jour de la date de fin de mission', 9);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('info_guarantee_end_date', 'info', 'Mise à jour de la date de fin de garantie', 10);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('archive', 'archive', 'Archivage', 11);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('task_create', 'task', null, 12);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('task_delete', 'task', null, 13);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('task_complete', 'task', null, 14);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('task_uncomplete', 'task', null, 15);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_account_manager', 'team', 'Mise à jour de l''account manager', 16);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_agent_1', 'team', 'Mise à jour de l''agent 1', 17);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_agent_2', 'team', 'Mise à jour de l''agent 2', 18);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_agent_1_com', 'team', 'Mise à jour de la com de l''agent 1', 19);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_agent_2_com', 'team', 'Mise à jour de la com de l''agent 2', 20);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_coo', 'team', 'Mise à jour de la cooptation', 21);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_coo_com', 'team', 'Mise à jour du montant de la cooptation', 22);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_bus', 'team', 'Mise à jour de l''apporteur d''affaires', 23);
insert into ref.evenement_note (code, type_evenement, libelle_fr, ordre) values ('team_bus_com', 'team', 'Mise à jour de l''apport d''affaires', 24);

-- ref.type_tache — task_event est vide au miroir (0/12) : déduit du préfixe.
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_free_onboarding', '[b]Onboarding[/b] du talent placé', true, 1, null, 'mandate_clo_free', 1);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_free_contract', 'Etablir le [b]Contrat[/b] avec entreprise', true, 1, null, 'mandate_clo_free', 2);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_free_start', 'Ecrire au talent pour son [b]1er jour[/b]', false, -1, null, 'mandate_clo_free', 3);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_free_news', 'Prendre des [b]nouvelles du talent[/b]', false, 15, null, 'mandate_clo_free', 4);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_free_cus_news', 'Prendre des [b]nouvelles du client[/b]', false, 15, null, 'mandate_clo_free', 5);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_cdi_invoice_cus', 'Envoi de la [b]facture client[/b]', true, 0, null, 'mandate_clo_cdi', 6);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_cdi_invoice_rec', 'Demander la [b]facture recruteur[/b]', true, 0, null, 'mandate_clo_cdi', 7);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_cdi_start_news', 'Ecrire au talent pour son [b]1er jour[/b]', false, -1, null, 'mandate_clo_cdi', 8);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_cdi_guar_news', 'Prendre des [b]nouvelles du talent[/b]', false, 7, null, 'mandate_clo_cdi', 9);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_cdi_m1_news', 'Prendre des [b]nouvelles du talent[/b]', false, 30, null, 'mandate_clo_cdi', 10);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_cdi_m3_news', 'Prendre des [b]nouvelles du talent[/b]', false, 90, null, 'mandate_clo_cdi', 11);
insert into ref.type_tache (code, gabarit_texte, est_admin, delai_relatif_jours, ancre, evenement, ordre) values ('mandate_clo_cdi_nps', 'Envoyer le [b]NPS Client[/b]', false, 1, null, 'mandate_clo_cdi', 12);
