import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Airplay,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftCircle,
  ArrowRight,
  ArrowRightCircle,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpLeft,
  ArrowUpRight,
  AtSign,
  Award,
  Ban,
  BarChart,
  BarChart2,
  Battery,
  BatteryCharging,
  Bell,
  BellOff,
  Bluetooth,
  Bold,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  Camera,
  CameraOff,
  Cast,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  Code,
  Coffee,
  Columns,
  Command,
  Compass,
  Component,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  Divide,
  DivideCircle,
  DivideSquare,
  DollarSign,
  Download,
  DownloadCloud,
  Droplet,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  Feather,
  File,
  FileMinus,
  FilePlus,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  FolderMinus,
  FolderPlus,
  Frown,
  Gift,
  Globe,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Image,
  Inbox,
  Info,
  Italic,
  Key,
  Layers,
  Layout,
  LayoutGrid,
  LifeBuoy,
  Link,
  Link2,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Music,
  Navigation,
  Navigation2,
  Octagon,
  Package,
  Paperclip,
  Pause,
  PauseCircle,
  PenTool,
  Phone,
  PieChart,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash,
  TrendingDown,
  TrendingUp,
  Truck,
  Tv,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Wind,
  Wrench,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

/**
 * Table de correspondance « nom d'icône Figma » -> « composant Lucide ».
 *
 * Le jeu du Figma est le jeu Feather au complet (285 noms `Property 1=icon-*`,
 * relevés entre Figma.md:48445 et Figma.md:57820), plus une rangée d'ajouts
 * maison. On ne redessine rien : lucide-react est le fork maintenu de Feather,
 * les tracés sont les mêmes à quelques redessins près.
 *
 * Les imports sont NOMMÉS et STATIQUES, volontairement. Un `import()` construit
 * depuis la chaîne du nom d'icône empêcherait le bundler d'élaguer : les 252
 * composants partiraient dans le paquet client au lieu des seuls utilisés.
 *
 * Trois pièges rencontrés, et c'est pourquoi la table est explicite plutôt que
 * calculée à la volée depuis le nom :
 *   1. 46 noms Feather ne sont plus que des alias dans Lucide (AlertTriangle
 *      renvoie sur triangle-alert, Filter sur funnel, Home sur house…). Ils
 *      fonctionnent, mais la table note le fichier canonique en commentaire.
 *   2. Deux noms existent des deux côtés en désignant des dessins DIFFÉRENTS :
 *      `Grid` (Lucide = grille de 9 cases) et `Slash` (Lucide = diagonale nue).
 *      Les mapper naïvement aurait changé le dessin sans rien casser à la
 *      compilation — le pire des bugs. Voir les commentaires ci-dessous.
 *   3. 33 noms du Figma n'ont AUCUN équivalent Lucide. Ils sont volontairement
 *      absents de la table, donc de `NomIcone` : les utiliser est une erreur de
 *      typage et non un carré vide à l'écran. Le détail est dans
 *      docs/ds-jetons-manquants-lot1.md.
 *
 * Couleur : le Figma peint ces icônes en #2D3648 (« WF Base/800 »), qui est la
 * couleur d'encre du kit de maquettage, pas une couleur de marque. Les icônes
 * suivent donc `currentColor` — noir, comme tout le texte du design system.
 */
export const ICONES = {
  'icon-activity': Activity,
  'icon-airplay': Airplay,
  'icon-alert-circle': AlertCircle, // alias Lucide de circle-alert
  'icon-alert-octagon': AlertOctagon, // alias Lucide de octagon-alert
  'icon-alert-triangle': AlertTriangle, // alias Lucide de triangle-alert
  'icon-align-center': AlignCenter, // alias Lucide de text-align-center
  'icon-align-justify': AlignJustify, // alias Lucide de text-align-justify
  'icon-align-left': AlignLeft, // alias Lucide de text-align-start
  'icon-align-right': AlignRight, // alias Lucide de text-align-end
  'icon-anchor': Anchor,
  'icon-aperture': Aperture,
  'icon-archive': Archive,
  'icon-arrow-down': ArrowDown,
  'icon-arrow-down-circle': ArrowDownCircle, // alias Lucide de circle-arrow-down
  'icon-arrow-down-left': ArrowDownLeft,
  'icon-arrow-down-right': ArrowDownRight,
  'icon-arrow-left': ArrowLeft,
  'icon-arrow-left-circle': ArrowLeftCircle, // alias Lucide de circle-arrow-left
  'icon-arrow-right': ArrowRight,
  'icon-arrow-right-circle': ArrowRightCircle, // alias Lucide de circle-arrow-right
  'icon-arrow-up': ArrowUp,
  'icon-arrow-up-circle': ArrowUpCircle, // alias Lucide de circle-arrow-up
  'icon-arrow-up-left': ArrowUpLeft,
  'icon-arrow-up-right': ArrowUpRight,
  'icon-at-sign': AtSign,
  'icon-award': Award,
  'icon-bar-chart': BarChart, // alias Lucide de chart-no-axes-column-increasing
  'icon-bar-chart-2': BarChart2, // alias Lucide de chart-no-axes-column
  'icon-battery': Battery,
  'icon-battery-charging': BatteryCharging,
  'icon-bell': Bell,
  'icon-bell-off': BellOff,
  'icon-bluetooth': Bluetooth,
  'icon-bold': Bold,
  'icon-book': Book,
  'icon-book-open': BookOpen,
  'icon-bookmark': Bookmark,
  'icon-box': Box,
  'icon-briefcase': Briefcase,
  'icon-calendar': Calendar,
  'icon-camera': Camera,
  'icon-camera-off': CameraOff,
  'icon-cast': Cast,
  'icon-check': Check,
  'icon-check-circle': CheckCircle, // alias Lucide de circle-check-big
  'icon-check-square': CheckSquare, // alias Lucide de square-check-big
  'icon-chevron-down': ChevronDown,
  'icon-chevron-left': ChevronLeft,
  'icon-chevron-right': ChevronRight,
  'icon-chevron-up': ChevronUp,
  'icon-chevrons-down': ChevronsDown,
  'icon-chevrons-left': ChevronsLeft,
  'icon-chevrons-right': ChevronsRight,
  'icon-chevrons-up': ChevronsUp,
  'icon-circle': Circle,
  'icon-clipboard': Clipboard,
  'icon-clock': Clock,
  'icon-cloud': Cloud,
  'icon-cloud-rain': CloudRain,
  'icon-cloud-snow': CloudSnow,
  'icon-code': Code,
  'icon-coffee': Coffee,
  'icon-columns': Columns, // alias Lucide de columns-2
  'icon-command': Command,
  'icon-compass': Compass,
  // Seul nom de la rangée d'ajouts maison (y=644) que Lucide couvre. Le dessin
  // n'est pas au pixel près : le Figma donne une boîte de 3..21 (Figma.md:56520),
  // Lucide v1.33 dessine 2.3..21.7 — même glyphe, redessiné entre-temps.
  'icon-component': Component,
  'icon-copy': Copy,
  'icon-corner-down-left': CornerDownLeft,
  'icon-corner-down-right': CornerDownRight,
  'icon-corner-left-down': CornerLeftDown,
  'icon-corner-left-up': CornerLeftUp,
  'icon-corner-right-down': CornerRightDown,
  'icon-corner-right-up': CornerRightUp,
  'icon-corner-up-left': CornerUpLeft,
  'icon-corner-up-right': CornerUpRight,
  'icon-cpu': Cpu,
  'icon-credit-card': CreditCard,
  'icon-crop': Crop,
  'icon-crosshair': Crosshair,
  'icon-database': Database,
  'icon-delete': Delete,
  'icon-disc': Disc,
  'icon-divide': Divide,
  'icon-divide-circle': DivideCircle, // alias Lucide de circle-divide
  'icon-divide-square': DivideSquare, // alias Lucide de square-divide
  'icon-dollar-sign': DollarSign,
  'icon-download': Download,
  'icon-download-cloud': DownloadCloud, // alias Lucide de cloud-download
  'icon-droplet': Droplet,
  'icon-edit': Edit, // alias Lucide de square-pen
  'icon-edit-2': Edit2, // alias Lucide de pen
  'icon-edit-3': Edit3, // alias Lucide de pen-line
  'icon-external-link': ExternalLink,
  'icon-eye': Eye,
  'icon-eye-off': EyeOff,
  'icon-fast-forward': FastForward,
  'icon-feather': Feather,
  'icon-file': File,
  'icon-file-minus': FileMinus,
  'icon-file-plus': FilePlus,
  'icon-file-text': FileText,
  'icon-film': Film,
  'icon-filter': Filter, // alias Lucide de funnel
  'icon-flag': Flag,
  'icon-folder': Folder,
  'icon-folder-minus': FolderMinus,
  'icon-folder-plus': FolderPlus,
  'icon-frown': Frown, // alias Lucide de face-slightly-frowning
  'icon-gift': Gift,
  'icon-globe': Globe,
  'icon-grid': LayoutGrid, // Feather grid = 4 carrés ; `Grid` pointe sur grid-3x3 (9 cases), faux
  'icon-hard-drive': HardDrive,
  'icon-hash': Hash,
  'icon-headphones': Headphones,
  'icon-heart': Heart,
  'icon-help-circle': HelpCircle, // alias Lucide de circle-question-mark
  'icon-hexagon': Hexagon,
  'icon-home': Home, // alias Lucide de house
  'icon-image': Image,
  'icon-inbox': Inbox,
  'icon-info': Info,
  'icon-italic': Italic,
  'icon-key': Key,
  'icon-layers': Layers,
  'icon-layout': Layout, // alias Lucide de panels-top-left
  'icon-life-buoy': LifeBuoy,
  'icon-link': Link,
  'icon-link-2': Link2,
  'icon-list': List,
  'icon-loader': Loader,
  'icon-lock': Lock,
  'icon-log-in': LogIn,
  'icon-log-out': LogOut,
  'icon-mail': Mail,
  'icon-map': Map,
  'icon-map-pin': MapPin,
  'icon-maximize-2': Maximize2,
  'icon-meh': Meh, // alias Lucide de face-neutral
  'icon-menu': Menu,
  'icon-message-circle': MessageCircle,
  'icon-message-square': MessageSquare,
  'icon-mic': Mic,
  'icon-mic-off': MicOff,
  'icon-minimize': Minimize,
  'icon-minimize-2': Minimize2,
  'icon-minus': Minus,
  'icon-minus-circle': MinusCircle, // alias Lucide de circle-minus
  'icon-minus-square': MinusSquare, // alias Lucide de square-minus
  'icon-monitor': Monitor,
  'icon-moon': Moon,
  'icon-more-horizontal': MoreHorizontal, // alias Lucide de ellipsis
  'icon-more-vertical': MoreVertical, // alias Lucide de ellipsis-vertical
  'icon-mouse-pointer': MousePointer,
  'icon-move': Move,
  'icon-music': Music,
  'icon-navigation': Navigation,
  'icon-navigation-2': Navigation2,
  'icon-octagon': Octagon,
  'icon-package': Package,
  'icon-paperclip': Paperclip,
  'icon-pause': Pause,
  'icon-pause-circle': PauseCircle, // alias Lucide de circle-pause
  'icon-pen-tool': PenTool,
  'icon-phone': Phone,
  'icon-pie-chart': PieChart, // alias Lucide de chart-pie
  'icon-play': Play,
  'icon-play-circle': PlayCircle, // alias Lucide de circle-play
  'icon-plus': Plus,
  'icon-plus-circle': PlusCircle, // alias Lucide de circle-plus
  'icon-plus-square': PlusSquare, // alias Lucide de square-plus
  'icon-power': Power,
  'icon-printer': Printer,
  'icon-radio': Radio,
  'icon-refresh-ccw': RefreshCcw,
  'icon-refresh-cw': RefreshCw,
  'icon-repeat': Repeat,
  'icon-rewind': Rewind,
  'icon-rotate-ccw': RotateCcw,
  'icon-rotate-cw': RotateCw,
  'icon-rss': Rss,
  'icon-save': Save,
  'icon-scissors': Scissors,
  'icon-search': Search,
  'icon-send': Send,
  'icon-server': Server,
  'icon-settings': Settings,
  'icon-share': Share,
  'icon-share-2': Share2,
  'icon-shield': Shield,
  'icon-shield-off': ShieldOff,
  'icon-shopping-bag': ShoppingBag,
  'icon-shopping-cart': ShoppingCart,
  'icon-shuffle': Shuffle,
  'icon-sidebar': Sidebar, // alias Lucide de panel-left
  'icon-skip-back': SkipBack,
  'icon-skip-forward': SkipForward,
  'icon-slash': Ban, // Feather slash = cercle barré ; `Slash` = diagonale nue, faux
  'icon-sliders': Sliders, // alias Lucide de sliders-vertical
  'icon-smartphone': Smartphone,
  'icon-smile': Smile, // alias Lucide de face-slightly-smiling
  'icon-speaker': Speaker,
  'icon-square': Square,
  'icon-star': Star,
  'icon-stop-circle': StopCircle, // alias Lucide de circle-stop
  'icon-sun': Sun,
  'icon-sunrise': Sunrise,
  'icon-sunset': Sunset,
  'icon-tablet': Tablet,
  'icon-tag': Tag,
  'icon-target': Target,
  'icon-terminal': Terminal,
  'icon-thermometer': Thermometer,
  'icon-thumbs-down': ThumbsDown,
  'icon-thumbs-up': ThumbsUp,
  'icon-toggle-left': ToggleLeft,
  'icon-toggle-right': ToggleRight,
  'icon-tool': Wrench, // renommage Feather tool -> Lucide wrench
  'icon-trash': Trash,
  'icon-trending-down': TrendingDown,
  'icon-trending-up': TrendingUp,
  'icon-truck': Truck,
  'icon-tv': Tv,
  'icon-type': Type,
  'icon-umbrella': Umbrella,
  'icon-underline': Underline,
  'icon-unlock': Unlock, // alias Lucide de lock-open
  'icon-upload': Upload,
  'icon-upload-cloud': UploadCloud, // alias Lucide de cloud-upload
  'icon-user': User,
  'icon-user-check': UserCheck,
  'icon-user-minus': UserMinus,
  'icon-user-plus': UserPlus,
  'icon-user-x': UserX,
  'icon-users': Users,
  'icon-video': Video,
  'icon-video-off': VideoOff,
  'icon-voicemail': Voicemail,
  'icon-volume': Volume,
  'icon-volume-1': Volume1,
  'icon-volume-2': Volume2,
  'icon-volume-x': VolumeX,
  'icon-wifi': Wifi,
  'icon-wifi-off': WifiOff,
  'icon-wind': Wind,
  'icon-x': X,
  'icon-x-circle': XCircle, // alias Lucide de circle-x
  'icon-x-octagon': XOctagon, // alias Lucide de octagon-x
  'icon-x-square': XSquare, // alias Lucide de square-x
  'icon-zap': Zap,
  'icon-zap-off': ZapOff,
  'icon-zoom-in': ZoomIn,
  'icon-zoom-out': ZoomOut,
} as const satisfies Record<string, LucideIcon>;

/** Union des noms d'icônes réellement disponibles (252 sur 285). */
export type NomIcone = keyof typeof ICONES;

/** Tous les noms, pour la page de référence du design system. */
export const NOMS_ICONES = Object.keys(ICONES) as NomIcone[];
